"""alertas cosecha, trazabilidad censo, mercado, logistica, vias, reset password, sms ussd, balance industrial

Revision ID: 17143d041330
Revises: 6e58291fcbdb
Create Date: 2026-09-17 00:31:48.044464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17143d041330'
down_revision = '6e58291fcbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estados_vias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('via', sa.String(length=150), nullable=False),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('actualizado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['actualizado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=False),
    sa.Column('expira_en', sa.DateTime(), nullable=False),
    sa.Column('usado', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_ussd_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('canal', sa.String(length=10), nullable=True),
    sa.Column('comando', sa.String(length=50), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('respuesta', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones_mercado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palmicultor_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('cantidad_toneladas', sa.Float(), nullable=False),
    sa.Column('precio_esperado', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['palmicultor_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balances_industriales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('pronostico_id', sa.Integer(), nullable=True),
    sa.Column('entrada_kg', sa.Float(), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=True),
    sa.Column('aceite_crudo_kg', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pronostico_id'], ['pronosticos_produccion.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ciclos_cosecha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_anticipacion_alerta', sa.Integer(), nullable=True))

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo_cosecha_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lote_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('enlace', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_notificaciones_lote_id', 'lotes', ['lote_id'], ['id'])
        batch_op.create_foreign_key('fk_notificaciones_ciclo_cosecha_id', 'ciclos_cosecha', ['ciclo_cosecha_id'], ['id'])

    with op.batch_alter_table('pronosticos_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registro_produccion_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('palmas_totales', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('palmas_improductivas_muestra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('palmas_productivas', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('palmas_productivas_muestreadas', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('promedio_estructuras', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distribucion_mensual', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_pronosticos_produccion_registro_produccion_id', 'registros_produccion', ['registro_produccion_id'], ['id'])

    with op.batch_alter_table('registros_produccion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fuente', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('creado_en', sa.DateTime(), nullable=True))

    with op.batch_alter_table('solicitudes_transporte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo_rechazo', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fecha_aceptacion', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True))

    with op.batch_alter_table('transportadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transportadores', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('solicitudes_transporte', schema=None) as batch_op:
        batch_op.drop_column('fecha_actualizacion')
        batch_op.drop_column('fecha_aceptacion')
        batch_op.drop_column('motivo_rechazo')

    with op.batch_alter_table('registros_produccion', schema=None) as batch_op:
        batch_op.drop_column('creado_en')
        batch_op.drop_column('fuente')

    with op.batch_alter_table('pronosticos_produccion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_pronosticos_produccion_registro_produccion_id', type_='foreignkey')
        batch_op.drop_column('distribucion_mensual')
        batch_op.drop_column('promedio_estructuras')
        batch_op.drop_column('palmas_productivas_muestreadas')
        batch_op.drop_column('palmas_productivas')
        batch_op.drop_column('palmas_improductivas_muestra')
        batch_op.drop_column('palmas_totales')
        batch_op.drop_column('registro_produccion_id')

    with op.batch_alter_table('notificaciones', schema=None) as batch_op:
        batch_op.drop_constraint('fk_notificaciones_ciclo_cosecha_id', type_='foreignkey')
        batch_op.drop_constraint('fk_notificaciones_lote_id', type_='foreignkey')
        batch_op.drop_column('enlace')
        batch_op.drop_column('lote_id')
        batch_op.drop_column('ciclo_cosecha_id')

    with op.batch_alter_table('ciclos_cosecha', schema=None) as batch_op:
        batch_op.drop_column('dias_anticipacion_alerta')

    op.drop_table('balances_industriales')
    op.drop_table('publicaciones_mercado')
    op.drop_table('sms_ussd_logs')
    op.drop_table('password_reset_tokens')
    op.drop_table('estados_vias')
    # ### end Alembic commands ###
