"""inicial

Revision ID: 6e58291fcbdb
Revises: 
Create Date: 2026-09-15 18:10:22.595852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e58291fcbdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('puntos_comercializacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_telefono'), ['telefono'], unique=True)

    op.create_table('compradores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('fincas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('municipio', sa.String(length=100), nullable=True),
    sa.Column('vereda', sa.String(length=100), nullable=True),
    sa.Column('coordenadas_lat', sa.Float(), nullable=True),
    sa.Column('coordenadas_long', sa.Float(), nullable=True),
    sa.Column('area_hectareas', sa.Float(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('titulo', sa.String(length=150), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transportadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('ubicacion', sa.String(length=200), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('lotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('bloque', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('area_hectareas', sa.Float(), nullable=True),
    sa.Column('anio_siembra', sa.Integer(), nullable=True),
    sa.Column('numero_palmas', sa.Integer(), nullable=True),
    sa.Column('material_sembrado', sa.String(length=50), nullable=True),
    sa.Column('topografia', sa.String(length=50), nullable=True),
    sa.Column('drenaje', sa.String(length=50), nullable=True),
    sa.Column('estado_sanitario', sa.String(length=50), nullable=True),
    sa.Column('numero_lineas', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('producto', sa.String(length=100), nullable=True),
    sa.Column('valor_moneda', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.Column('fuente', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transportador_id', sa.Integer(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo_vehiculo', sa.String(length=50), nullable=True),
    sa.Column('capacidad_toneladas', sa.Float(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['transportador_id'], ['transportadores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('ciclos_cosecha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ultima_cosecha', sa.Date(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('duracion_dias', sa.Integer(), nullable=True),
    sa.Column('proxima_fecha_estimada', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pronosticos_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha_calculo', sa.DateTime(), nullable=True),
    sa.Column('racimos_estimados', sa.Float(), nullable=True),
    sa.Column('peso_promedio', sa.Float(), nullable=True),
    sa.Column('produccion_estimada_kg', sa.Float(), nullable=True),
    sa.Column('produccion_estimada_ton', sa.Float(), nullable=True),
    sa.Column('metodologia', sa.String(length=100), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_polinizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('numero_inflorescencias', sa.Integer(), nullable=True),
    sa.Column('cantidad_producto', sa.Float(), nullable=True),
    sa.Column('gramos_por_inflorescencia', sa.Float(), nullable=True),
    sa.Column('responsable', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_produccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('palmas_evaluadas', sa.Integer(), nullable=True),
    sa.Column('inflorescencias', sa.Integer(), nullable=True),
    sa.Column('racimos_pequenos', sa.Integer(), nullable=True),
    sa.Column('racimos_medianos', sa.Integer(), nullable=True),
    sa.Column('racimos_maduros', sa.Integer(), nullable=True),
    sa.Column('racimos_totales', sa.Integer(), nullable=True),
    sa.Column('palmas_improductivas', sa.Integer(), nullable=True),
    sa.Column('peso_promedio_racimo', sa.Float(), nullable=True),
    sa.Column('fruto_suelto', sa.Float(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('solicitudes_transporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('palmicultor_id', sa.Integer(), nullable=False),
    sa.Column('transportador_id', sa.Integer(), nullable=True),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=True),
    sa.Column('comprador_id', sa.Integer(), nullable=True),
    sa.Column('fecha_solicitud', sa.DateTime(), nullable=True),
    sa.Column('fecha_servicio', sa.Date(), nullable=True),
    sa.Column('hora_servicio', sa.Time(), nullable=True),
    sa.Column('cantidad_estimada', sa.Float(), nullable=True),
    sa.Column('origen', sa.String(length=200), nullable=True),
    sa.Column('destino', sa.String(length=200), nullable=True),
    sa.Column('tarifa_sugerida', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('tarifa_acordada', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['compradores.id'], ),
    sa.ForeignKeyConstraint(['finca_id'], ['fincas.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lotes.id'], ),
    sa.ForeignKeyConstraint(['palmicultor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['transportador_id'], ['transportadores.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solicitudes_transporte')
    op.drop_table('registros_produccion')
    op.drop_table('registros_polinizacion')
    op.drop_table('pronosticos_produccion')
    op.drop_table('ciclos_cosecha')
    op.drop_table('vehiculos')
    op.drop_table('precios')
    op.drop_table('lotes')
    op.drop_table('transportadores')
    op.drop_table('notificaciones')
    op.drop_table('fincas')
    op.drop_table('compradores')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_telefono'))

    op.drop_table('usuarios')
    op.drop_table('puntos_comercializacion')
    # ### end Alembic commands ###
